# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LNRefreshDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LNRefreshDemo
  pod 'LNRefresh'

  target 'LNRefreshDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LNRefreshDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
